version: "3"

x-uffizzi:
  ingress:
    service: acmesh
    port: 7681

services:

  acmesh:
    image: "${ACME_IMAGE}"
    volumes: 
    #   # - ./uffizzi/entrypoint.sh:/acme.sh-docker.sh:ro
      - ./acme.sh:/acme.sh
    ports:
    - "7700:7700"
    - "7681:7681"
    entrypoint: ["tini", "--"]
    command: 
     - "ttyd /bin/zsh ttyd /entry.sh"
    deploy:
      resources:
        limits:
          memory: 4000M
