version: "3"

x-uffizzi:
  ingress:
    service: acmesh
    port: 7681

services:

  acmesh:
    image: "${ACME_IMAGE}"
    volumes: 
    #   # - ./uffizzi/entrypoint.sh:/acme.sh-docker.sh:ro
      - ./acme.sh:/acme.sh
    entrypoint: ["/bin/sh", "-c"]
    command: ["ttyd entry.sh daemon"]       
    # entrypoint: ["/bin/bash", "-c"]
    # command: ["ttyd acme.sh"]    
    ports:
    - "7700:7700"
    - "7681:7681"
    deploy:
      resources:
        limits:
          memory: 4000M
