version: "3"

x-uffizzi:
  ingress:
    service: acmesh
    port: 7681

services:

  acmesh:
    image: "${ACME_IMAGE}"
    volumes: 
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./acme.sh:/acme.sh
    ports:
    - "7700:7700"
    - "7681:7681"
    entrypoint: ["/bin/bash", "-c"]
    command: ["ttyd /entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: 2000M
