version: "3"

x-uffizzi:
  ingress:
    service: acmesh
    port: 7681

services:

  acmesh:
    image: "${ACME_IMAGE}"
    volumes: 
      - ./acme.sh:/acme.sh
    # entrypoint: ["/bin/bash", "-c"]
    # command: ["/bin/bash -c ttyd acme.sh"]       
    # entrypoint: ["/bin/bash", "-c"]
    command: ["acme.sh", "tail", "-f", "/dev/null"]    
    ports:
    - "7700:7700"
    - "7681:7681"
    deploy:
      resources:
        limits:
          memory: 4000M
