version: "3"

x-uffizzi:
  ingress:
    service: acmesh
    port: 7681

services:

  acmesh:
    image: "${ACME_IMAGE}"
    volumes: 
      - ./acme.sh:/acme.sh
    # entrypoint: ["/bin/bash", "-c"]
    # command: ["/bin/bash -c ttyd acme.sh"]       
    entrypoint: ["tini", "--", "/bin/bash", "-c"]
    # command: ["ttyd acme.sh", "tail", "-f", "/dev/null"]  
    command: ["ttyd -m no limit /entry.sh --help"]   
    ports:
    - "7700:7700"
    - "7681:7681"
    deploy:
      resources:
        limits:
          memory: 4000M
